---
title: FAPAR 2014-present (raster 300 m), global, 10-daily – version 1
---
### About
Quantifies the fraction of the solar radiation absorbed by live plants for photosynthesis. Every 10-days estimates are available in near real time at global scale in the spatial resolution of about 300 m from January 2014 to June 2020 based upon PROBA-V data with version 1.0 and from July 2020 onwards based upon Sentinel-3/OLCI data with version 1.1.

[View this dataset in Copernicus Browser](https://browser.dataspace.copernicus.eu/?zoom=9&lat=46.02622&lng=14.5253&themeId=DEFAULT-THEME&datasetId=COPERNICUS_CLMS_FAPAR_300M_10DAILY&fromTime=2014-01-01T00%3A00%3A00.000Z&toTime=2025-06-12T14:36:02.076208&layerId=FAPAR&demSource3D=%22MAPZEN%22&cloudCoverage=30&dateMode=SINGLE&clmsSelectedPath=Vegetation%20Properties&clmsSelectedCollection=COPERNICUS_CLMS_FAPAR_300M_10DAILY)

{< include _header.qmd >}

### Collection ID
| Version | ID |
|:---------:|----|
|None|46db50f9-3de8-48ca-900f-fb87addc620a
|RT0|3dc7fbf5-788f-483e-977e-2b56861c0f22
|RT1|c14ecd63-b276-495d-8ad5-1b4c25ee538b
|RT2|a9b7f384-668a-4cef-9e45-108605a12329
|RT6|50b8f946-3f2e-4292-a821-996fb2ce215c

### Date range

2014-present

### Bands

| Name          | Description  |   Units |  Source format | Range | Scaling | Offset |
|---------------|--------------|---------|----------------|-------|---------|--------|
|FAPAR|Fraction of Absorbed Photosynthetically Active Radiation|-|UINT8|0-0.94|1/250|0|

### Evalscript

To use this dataset with sentinel hub APIs you can use the examples provided in the [Sentinel Hub custom scripts repository.](https://github.com/eu-cdse/sentinel-hub-custom-scripts/tree/clms/clms/bio-geophysical-parameters/vegetation/vegetation-properties/fapar_global_300m_10daily_v1)
