---
title: LST (TCI) 2017-2021 (raster 5 km), global, 10-daily – version 1
---
## About
[Official documentation](https://land.copernicus.eu/en/products/temperature-and-reflectance/10-daily-land-surface-temperature-thermal-condition-index-global-v1-0-5km)

Provides a statistical overview of the land surface temperature over each 10-day compositing period regardless of any specific hour and every geostationary sensor image pixel. The data are available at global scale in the spatial resolution of about 5 km and covers the period from January 2017 to January 2021.

[View this dataset in Copernicus Browser](https://browser.dataspace.copernicus.eu/?zoom=9&lat=46.02622&lng=14.5253&themeId=DEFAULT-THEME&datasetId=COPERNICUS_CLMS_FAPAR_300M_10DAILY&fromTime=2014-01-01T00%3A00%3A00.000Z&toTime=2025-06-13T11:41:00.881274&layerId=FAPAR&demSource3D=%22MAPZEN%22&cloudCoverage=30&dateMode=SINGLE&clmsSelectedPath=Vegetation%20Properties&clmsSelectedCollection=COPERNICUS_CLMS_FAPAR_300M_10DAILY)

{{< include /APIs/SentinelHub/Data/clms/_header.qmd >}}

### Collection ID

2dd2d9e0-8f02-4adc-8b14-dea6c56e8d2b

## Date range

2017-2021

## Bands

| Name          | Description  |   Units |  Source format | Range | Scaling | Offset |
|---------------|--------------|---------|----------------|-------|---------|--------|
|TCI|Thermal Condition Index for the 10-day composite period|-|INT16|0-1|1/10000|0|
|FRAC_VALID_OBS|Fraction of valid observations|-|INT16|0-1|1/100|0|
|MAX|Maximum LST values observed during the 10-day compositing period|K|INT16|203.15-353.15|1/100|273.15|
|MEDIAN|Median LST values observed during the 10-day compositing period|K|INT16|203.15-353.15|1/100|273.15|
|MIN|Minimum LST values observed during the 10-day compositing period|K|INT16|203.15-353.15|1/100|273.15|

## Evalscript

To use this dataset with Sentinel Hub APIs you can use the examples provided in the [Sentinel Hub custom scripts repository.](https://github.com/eu-cdse/sentinel-hub-custom-scripts/tree/clms/clms/bio-geophysical-parameters/temperature-and-reflectance/land-surface-temperature/lst-tci_global_5km_10daily_v1)

An evalscript (or "custom script") is a piece of Javascript code which defines how the data shall be processed by Sentinel Hub and what values the service shall return. It is a required part of any [process](/APIs/SentinelHub/Process.qmd), [batch processing](/APIs/SentinelHub/Batch.qmd) or [OGC request](/APIs/SentinelHub/OGC.qmd).

Evalscripts can use any JavaScript function or language structures, along with certain [utility functions](/APIs/SentinelHub/Evalscript/Functions.qmd) we provide for your convenience. For running evalscripts we use the [Chrome V8](https://v8.dev/){target="_blank"} JavaScript engine.
