---
title: Temperature and Reflectance
listing:
    type: table
    sort: false
    fields: [title, description]
    sort-ui: false
    contents: Temperature_And_Reflectance/*
---

## Overview

Earth’s “energy


budget” refers to the interplay between the incoming solar radiation and the outgoing thermal radiation. Understanding this balance is crucial for weather forecasting, assessing climate patterns, and environmental sustainability. Temperature parameters, such land and water surface temperatures, provide valuable insights into this balance by contributing to our understanding of soil health, plant growth, water quality, and aquatic ecosystems. Reflectance parameters further inform this energy equation by quantifying how much sunlight is absorbed or reflected back into space. Together, temperature and reflectance data provide a comprehensive view of the Earth's energy dynamics, enabling informed decisions in areas such as climate change mitigation, sustainable land use, water management, and biodiversity conservation.

The Temperature and Reflectance product group offers datasets at the global scale and with resolutions ranging from 300 m to 5 km. The associated datasets not only provide robust time series but also continue to support a wide array of applications including agriculture, climate analysis, water resource management, and ecosystem preservation. Their availability as continuous time-series further enhances their value in ongoing environmental analysis and decision-making processes.
