---
title: NDVI (LTS) 1999-2017 (raster 1 km), global, 10-daily – version 2
---
## About
[Official documentation](https://land.copernicus.eu/en/products/vegetation/normalised-difference-vegetation-index-long-term-statistics-v2-0-1km)

Based upon SPOT/VEGETATION and PROBA-V NDVI 1km version 2, long-term statistics include the minimum, median, maximum, mean, standard deviation and the number of observations over the 19-years period 1999-2017.

[View this dataset in Copernicus Browser](https://browser.dataspace.copernicus.eu/?zoom=9&lat=46.02622&lng=14.5253&themeId=DEFAULT-THEME&datasetId=COPERNICUS_CLMS_FAPAR_300M_10DAILY&fromTime=2014-01-01T00%3A00%3A00.000Z&toTime=2025-06-13T11:41:00.876216&layerId=FAPAR&demSource3D=%22MAPZEN%22&cloudCoverage=30&dateMode=SINGLE&clmsSelectedPath=Vegetation%20Properties&clmsSelectedCollection=COPERNICUS_CLMS_FAPAR_300M_10DAILY)

{{< include /APIs/SentinelHub/Data/clms/_header.qmd >}}

### Collection ID

35976c51-6ea0-4feb-b433-a24706d621fa

## Date range

1999-2017

## Bands

| Name          | Description  |   Units |  Source format | Range | Scaling | Offset |
|---------------|--------------|---------|----------------|-------|---------|--------|
|NDVI_MAX_LTS|Maximum of the physical NDVI values|-|UINT8|-0.08-0.92|1/250|-0.08|
|NDVI_MEAN_LTS|Mean of the physical NDVI values|-|UINT8|-0.08-0.92|1/250|-0.08|
|NDVI_MEDIAN_LTS|Median of the physical NDVI values|-|UINT8|-0.08-0.92|1/250|-0.08|
|NDVI_MIN_LTS|Minimum of the physical NDVI values|-|UINT8|-0.08-0.92|1/250|-0.08|
|NDVI_NOBS_LTS|Number of physical NDVI values used to calculate the statistics|-|UINT8|0-19|1|0|
|NDVI_STDEV_LTS|Standard deviation of physical NDVI values|-|UINT8|0-1|1/250|0|

## Evalscript

To use this dataset with Sentinel Hub APIs you can use the examples provided in the [Sentinel Hub custom scripts repository.](https://github.com/eu-cdse/sentinel-hub-custom-scripts/tree/clms/clms/bio-geophysical-parameters/vegetation/vegetation-indices/ndvi-lts_global_1km_10daily_v2)

An evalscript (or "custom script") is a piece of Javascript code which defines how the data shall be processed by Sentinel Hub and what values the service shall return. It is a required part of any [process](/APIs/SentinelHub/Process.qmd), [batch processing](/APIs/SentinelHub/Batch.qmd) or [OGC request](/APIs/SentinelHub/OGC.qmd).

Evalscripts can use any JavaScript function or language structures, along with certain [utility functions](/APIs/SentinelHub/Evalscript/Functions.qmd) we provide for your convenience. For running evalscripts we use the [Chrome V8](https://v8.dev/){target="_blank"} JavaScript engine.
